### ISSUE TITLE
Updating Wiki early

### ISSUE THREAD

**Issue by ttk2** [gmlaxfanatic/FactoryMod#23]
since people constantly refer to the factory mod wiki for recipes is has been an issue when the wiki updates before the changes are live, thus resulting in players wasting resources for recipes that work differently or outright do not exist. I don't quite have a good way to solve this issue, but it does need to be addressed.

**Comment by gmlaxfanatic** [comment]
I think this is mainly due to a temporary mistake I made. Normally I'll update the wiki when i send you a jar, so it ends up being ahead by like 10 hours max usually. Recently I accidentally generated the wiki page including the new XP recipes even though that was not planned to be deployed on the main server, and then left for a drunken float trip and so the wiki has been out of sync for the last two days which shouldn't have happened.

**Comment by ttk2** [comment]
its not the end of the world, but some people have been complaining, its
possible we should have a 'produciton' wiki.
