### ISSUE TITLE
Animal husbandry factory repair costs at 100% rather than 10%

### ISSUE THREAD

**Issue by Peter5930** [gmlaxfanatic/FactoryMod#50]
Mine just ate half a stack each of iron blocks, haybales and golden apples when I went to repair it, and it's still only at 50% health.

**Comment by UselessFodder** [comment]
Well, I'm looking at the factory and it looks like it should work as normal. I'm still pretty confused as to what 'repair_multiple' exactly means, though. It seems to vary widely from factory to factory.

> repair_multiple: 10
>     repair_inputs:
>         Iron Block:
>         material: IRON_BLOCK
>         amount: 6
>     Hay Bale:
>         material: HAY_BLOCK
>         amount: 6
>     Golden Apple:
>         material: GOLDEN_APPLE
>         amount: 6
>         durability: 0

**Comment by gmlaxfanatic** [comment]
So yeah, repair multiple is weird and forced due to the inflexibility of the java code unfortunately. Its the solution to the problem that while there is a total repair amount for a factory, we want it to be able to be repaired in smaller increments (commonly the smallest increments possible still giving whole amounts).  The code can't do this easily, so instead what the config dictates is the increment of repair, and then the repair multiple dictates the number of increments to go from broken to 100%.

So the current code calls for 60 of each of those materials 6x10 to fully repair the factory. This should be changed to something that approximates 10% of the construction (input) cost.
